<?php require('template/header.phtml'); ?>

<div class="result-text">
    <h1>Thank you for your purchase!</h1>
    <p>You have successfully bought the following item:</p>
    <h2><?php echo $view->item; ?></h2>
    <p>The cost was: <strong><?php echo $view->cost; ?></strong></p>
    <p style="margin-top: 30px;"><a href="shop.php" class="btn btn-primary">Return to Shop</a></p>
</div>

<?php require('template/footer.phtml'); ?>
