<?php require('template/header.phtml') ?>

<table class="table table-bordered border-dark" style="margin-top: 50px;">
    <thead>
    <tr>
        <th>Item</th>
        <th>Description</th>
        <th>Cost</th>
        <th>Purchase</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Sony TV</td>
        <td>32" LCD Widescreen</td>
        <td>£950</td>
        <td><a href="purchase.php?item=Sony+TV&cost=£950">buy</a></td>
    </tr>
    <tr>
        <td>Panasonic DVD</td>
        <td>DVD Player</td>
        <td>£80</td>
        <td><a href="purchase.php?item=Panasonic+DVD&cost=£80">buy</a></td>
    </tr>
    <tr>
        <td>Philips Video</td>
        <td>VHS Video Recorder</td>
        <td>£110</td>
        <td><a href="purchase.php?item=Philips+Video&cost=£110">buy</a></td>
    </tr>
    </tbody>
</table>

<?php require('template/footer.phtml') ?>
