<!--This is a reusable footer for all pages-->

</main>
</div>
</div>

<footer class="footer mt-auto py-3 bg-dark">
    <div class="container">
        <div id="footer" class="col-xs-12">
            <p class="text-light text-center">Web-site development using the PHP MVC design pattern and the Bootstrap
                CSS framework</p>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>

</body>
</html>
